use async_graphql::InputObject;

mod conversion;
use crate::filters::{
    AccountFilter, BlockChangedFilter, DomainFilter, RegistrationFilter, ResolverFilter,
};
use storage::TextOperatorFilter;

#[derive(Debug, Clone, Default)]
pub struct EventFilter {
    pub id: Option<String>,
    pub id_not: Option<String>,
    pub id_gt: Option<String>,
    pub id_lt: Option<String>,
    pub id_gte: Option<String>,
    pub id_lte: Option<String>,
    pub id_in: Option<Vec<String>>,
    pub id_not_in: Option<Vec<String>>,
    pub parent_id: Option<String>,
    pub parent_id_not: Option<String>,
    pub parent_id_gt: Option<String>,
    pub parent_id_lt: Option<String>,
    pub parent_id_gte: Option<String>,
    pub parent_id_lte: Option<String>,
    pub parent_id_in: Option<Vec<String>>,
    pub parent_id_not_in: Option<Vec<String>>,
    pub parent_id_contains: Option<String>,
    pub parent_id_contains_nocase: Option<String>,
    pub parent_id_not_contains: Option<String>,
    pub parent_id_not_contains_nocase: Option<String>,
    pub parent_id_starts_with: Option<String>,
    pub parent_id_starts_with_nocase: Option<String>,
    pub parent_id_not_starts_with: Option<String>,
    pub parent_id_not_starts_with_nocase: Option<String>,
    pub parent_id_ends_with: Option<String>,
    pub parent_id_ends_with_nocase: Option<String>,
    pub parent_id_not_ends_with: Option<String>,
    pub parent_id_not_ends_with_nocase: Option<String>,
    pub registration_filter: Option<Box<RegistrationFilter>>,
    pub block_number: Option<i32>,
    pub block_number_not: Option<i32>,
    pub block_number_gt: Option<i32>,
    pub block_number_lt: Option<i32>,
    pub block_number_gte: Option<i32>,
    pub block_number_lte: Option<i32>,
    pub block_number_in: Option<Vec<i32>>,
    pub block_number_not_in: Option<Vec<i32>>,
    pub transaction_id: Option<String>,
    pub transaction_id_not: Option<String>,
    pub transaction_id_gt: Option<String>,
    pub transaction_id_lt: Option<String>,
    pub transaction_id_gte: Option<String>,
    pub transaction_id_lte: Option<String>,
    pub transaction_id_in: Option<Vec<String>>,
    pub transaction_id_not_in: Option<Vec<String>>,
    pub transaction_id_contains: Option<String>,
    pub transaction_id_not_contains: Option<String>,
    pub owner_id: Option<String>,
    pub owner_id_not: Option<String>,
    pub owner_id_gt: Option<String>,
    pub owner_id_lt: Option<String>,
    pub owner_id_gte: Option<String>,
    pub owner_id_lte: Option<String>,
    pub owner_id_in: Option<Vec<String>>,
    pub owner_id_not_in: Option<Vec<String>>,
    pub owner_id_contains: Option<String>,
    pub owner_id_not_contains: Option<String>,
    pub parent_domain_id: Option<String>,
    pub parent_domain_id_ops: TextOperatorFilter,
    pub parent_domain_filter: Option<Box<DomainFilter>>,
    pub resolver_id: Option<String>,
    pub resolver_id_ops: TextOperatorFilter,
    pub resolver_filter: Option<Box<ResolverFilter>>,
    pub registrant_id: Option<String>,
    pub registrant_id_ops: TextOperatorFilter,
    pub registrant_filter: Option<Box<AccountFilter>>,
    pub new_owner_id: Option<String>,
    pub new_owner_id_ops: TextOperatorFilter,
    pub new_owner_filter: Option<Box<AccountFilter>>,
    pub addr_id: Option<String>,
    pub addr_id_not: Option<String>,
    pub addr_id_gt: Option<String>,
    pub addr_id_lt: Option<String>,
    pub addr_id_gte: Option<String>,
    pub addr_id_lte: Option<String>,
    pub addr_id_in: Option<Vec<String>>,
    pub addr_id_not_in: Option<Vec<String>>,
    pub addr_id_contains: Option<String>,
    pub addr_id_not_contains: Option<String>,
    pub addr_filter: Option<Box<AccountFilter>>,
    pub domain_filter: Option<Box<DomainFilter>>,
    pub owner_filter: Option<Box<AccountFilter>>,
    pub name: Option<String>,
    pub name_not: Option<String>,
    pub name_gt: Option<String>,
    pub name_lt: Option<String>,
    pub name_gte: Option<String>,
    pub name_lte: Option<String>,
    pub name_in: Option<Vec<String>>,
    pub name_not_in: Option<Vec<String>>,
    pub name_contains: Option<String>,
    pub name_contains_nocase: Option<String>,
    pub name_not_contains: Option<String>,
    pub name_not_contains_nocase: Option<String>,
    pub name_starts_with: Option<String>,
    pub name_starts_with_nocase: Option<String>,
    pub name_not_starts_with: Option<String>,
    pub name_not_starts_with_nocase: Option<String>,
    pub name_ends_with: Option<String>,
    pub name_ends_with_nocase: Option<String>,
    pub name_not_ends_with: Option<String>,
    pub name_not_ends_with_nocase: Option<String>,
    pub fuses: Option<i32>,
    pub fuses_not: Option<i32>,
    pub fuses_gt: Option<i32>,
    pub fuses_lt: Option<i32>,
    pub fuses_gte: Option<i32>,
    pub fuses_lte: Option<i32>,
    pub fuses_in: Option<Vec<i32>>,
    pub fuses_not_in: Option<Vec<i32>>,
    pub ttl: Option<String>,
    pub ttl_not: Option<String>,
    pub ttl_gt: Option<String>,
    pub ttl_lt: Option<String>,
    pub ttl_gte: Option<String>,
    pub ttl_lte: Option<String>,
    pub ttl_in: Option<Vec<String>>,
    pub ttl_not_in: Option<Vec<String>>,
    pub expiry_date: Option<String>,
    pub expiry_date_not: Option<String>,
    pub expiry_date_gt: Option<String>,
    pub expiry_date_lt: Option<String>,
    pub expiry_date_gte: Option<String>,
    pub expiry_date_lte: Option<String>,
    pub expiry_date_in: Option<Vec<String>>,
    pub expiry_date_not_in: Option<Vec<String>>,
    pub coin_type: Option<String>,
    pub coin_type_not: Option<String>,
    pub coin_type_gt: Option<String>,
    pub coin_type_lt: Option<String>,
    pub coin_type_gte: Option<String>,
    pub coin_type_lte: Option<String>,
    pub coin_type_in: Option<Vec<String>>,
    pub coin_type_not_in: Option<Vec<String>>,
    pub content_type: Option<String>,
    pub content_type_not: Option<String>,
    pub content_type_gt: Option<String>,
    pub content_type_lt: Option<String>,
    pub content_type_gte: Option<String>,
    pub content_type_lte: Option<String>,
    pub content_type_in: Option<Vec<String>>,
    pub content_type_not_in: Option<Vec<String>>,
    pub x: Option<String>,
    pub x_not: Option<String>,
    pub x_gt: Option<String>,
    pub x_lt: Option<String>,
    pub x_gte: Option<String>,
    pub x_lte: Option<String>,
    pub x_in: Option<Vec<String>>,
    pub x_not_in: Option<Vec<String>>,
    pub x_contains: Option<String>,
    pub x_not_contains: Option<String>,
    pub y: Option<String>,
    pub y_not: Option<String>,
    pub y_gt: Option<String>,
    pub y_lt: Option<String>,
    pub y_gte: Option<String>,
    pub y_lte: Option<String>,
    pub y_in: Option<Vec<String>>,
    pub y_not_in: Option<Vec<String>>,
    pub y_contains: Option<String>,
    pub y_not_contains: Option<String>,
    pub key: Option<String>,
    pub key_not: Option<String>,
    pub key_gt: Option<String>,
    pub key_lt: Option<String>,
    pub key_gte: Option<String>,
    pub key_lte: Option<String>,
    pub key_in: Option<Vec<String>>,
    pub key_not_in: Option<Vec<String>>,
    pub key_contains: Option<String>,
    pub key_contains_nocase: Option<String>,
    pub key_not_contains: Option<String>,
    pub key_not_contains_nocase: Option<String>,
    pub key_starts_with: Option<String>,
    pub key_starts_with_nocase: Option<String>,
    pub key_not_starts_with: Option<String>,
    pub key_not_starts_with_nocase: Option<String>,
    pub key_ends_with: Option<String>,
    pub key_ends_with_nocase: Option<String>,
    pub key_not_ends_with: Option<String>,
    pub key_not_ends_with_nocase: Option<String>,
    pub value: Option<String>,
    pub value_not: Option<String>,
    pub value_gt: Option<String>,
    pub value_lt: Option<String>,
    pub value_gte: Option<String>,
    pub value_lte: Option<String>,
    pub value_in: Option<Vec<String>>,
    pub value_not_in: Option<Vec<String>>,
    pub value_contains: Option<String>,
    pub value_contains_nocase: Option<String>,
    pub value_not_contains: Option<String>,
    pub value_not_contains_nocase: Option<String>,
    pub value_starts_with: Option<String>,
    pub value_starts_with_nocase: Option<String>,
    pub value_not_starts_with: Option<String>,
    pub value_not_starts_with_nocase: Option<String>,
    pub value_ends_with: Option<String>,
    pub value_ends_with_nocase: Option<String>,
    pub value_not_ends_with: Option<String>,
    pub value_not_ends_with_nocase: Option<String>,
    pub hash: Option<String>,
    pub hash_not: Option<String>,
    pub hash_gt: Option<String>,
    pub hash_lt: Option<String>,
    pub hash_gte: Option<String>,
    pub hash_lte: Option<String>,
    pub hash_in: Option<Vec<String>>,
    pub hash_not_in: Option<Vec<String>>,
    pub hash_contains: Option<String>,
    pub hash_not_contains: Option<String>,
    pub interface_id: Option<String>,
    pub interface_id_not: Option<String>,
    pub interface_id_gt: Option<String>,
    pub interface_id_lt: Option<String>,
    pub interface_id_gte: Option<String>,
    pub interface_id_lte: Option<String>,
    pub interface_id_in: Option<Vec<String>>,
    pub interface_id_not_in: Option<Vec<String>>,
    pub interface_id_contains: Option<String>,
    pub interface_id_not_contains: Option<String>,
    pub implementer: Option<String>,
    pub implementer_not: Option<String>,
    pub implementer_gt: Option<String>,
    pub implementer_lt: Option<String>,
    pub implementer_gte: Option<String>,
    pub implementer_lte: Option<String>,
    pub implementer_in: Option<Vec<String>>,
    pub implementer_not_in: Option<Vec<String>>,
    pub implementer_contains: Option<String>,
    pub implementer_not_contains: Option<String>,
    pub target: Option<String>,
    pub target_not: Option<String>,
    pub target_gt: Option<String>,
    pub target_lt: Option<String>,
    pub target_gte: Option<String>,
    pub target_lte: Option<String>,
    pub target_in: Option<Vec<String>>,
    pub target_not_in: Option<Vec<String>>,
    pub target_contains: Option<String>,
    pub target_not_contains: Option<String>,
    pub is_authorized: Option<bool>,
    pub is_authorized_not: Option<bool>,
    pub is_authorized_in: Option<Vec<bool>>,
    pub is_authorized_not_in: Option<Vec<bool>>,
    pub version: Option<String>,
    pub version_not: Option<String>,
    pub version_gt: Option<String>,
    pub version_lt: Option<String>,
    pub version_gte: Option<String>,
    pub version_lte: Option<String>,
    pub version_in: Option<Vec<String>>,
    pub version_not_in: Option<Vec<String>>,
    pub and: Option<Vec<EventFilter>>,
    pub or: Option<Vec<EventFilter>>,
}

#[derive(Debug, Clone, InputObject, Default)]
pub(crate) struct BaseEventFilter {
    pub id: Option<String>,
    #[graphql(name = "id_not")]
    pub id_not: Option<String>,
    #[graphql(name = "id_gt")]
    pub id_gt: Option<String>,
    #[graphql(name = "id_lt")]
    pub id_lt: Option<String>,
    #[graphql(name = "id_gte")]
    pub id_gte: Option<String>,
    #[graphql(name = "id_lte")]
    pub id_lte: Option<String>,
    #[graphql(name = "id_in")]
    pub id_in: Option<Vec<String>>,
    #[graphql(name = "id_not_in")]
    pub id_not_in: Option<Vec<String>>,
    #[graphql(name = "blockNumber")]
    pub block_number: Option<i32>,
    #[graphql(name = "blockNumber_not")]
    pub block_number_not: Option<i32>,
    #[graphql(name = "blockNumber_gt")]
    pub block_number_gt: Option<i32>,
    #[graphql(name = "blockNumber_lt")]
    pub block_number_lt: Option<i32>,
    #[graphql(name = "blockNumber_gte")]
    pub block_number_gte: Option<i32>,
    #[graphql(name = "blockNumber_lte")]
    pub block_number_lte: Option<i32>,
    #[graphql(name = "blockNumber_in")]
    pub block_number_in: Option<Vec<i32>>,
    #[graphql(name = "blockNumber_not_in")]
    pub block_number_not_in: Option<Vec<i32>>,
    #[graphql(name = "transactionID")]
    pub transaction_id: Option<String>,
    #[graphql(name = "transactionID_not")]
    pub transaction_id_not: Option<String>,
    #[graphql(name = "transactionID_gt")]
    pub transaction_id_gt: Option<String>,
    #[graphql(name = "transactionID_lt")]
    pub transaction_id_lt: Option<String>,
    #[graphql(name = "transactionID_gte")]
    pub transaction_id_gte: Option<String>,
    #[graphql(name = "transactionID_lte")]
    pub transaction_id_lte: Option<String>,
    #[graphql(name = "transactionID_in")]
    pub transaction_id_in: Option<Vec<String>>,
    #[graphql(name = "transactionID_not_in")]
    pub transaction_id_not_in: Option<Vec<String>>,
    #[graphql(name = "transactionID_contains")]
    pub transaction_id_contains: Option<String>,
    #[graphql(name = "transactionID_not_contains")]
    pub transaction_id_not_contains: Option<String>,
    #[graphql(name = "_change_block")]
    pub change_block: Option<BlockChangedFilter>,
}

impl BaseEventFilter {
    pub(crate) fn apply(self, filter: &mut EventFilter) {
        filter.id = self.id;
        filter.id_not = self.id_not;
        filter.id_gt = self.id_gt;
        filter.id_lt = self.id_lt;
        filter.id_gte = self.id_gte;
        filter.id_lte = self.id_lte;
        filter.id_in = self.id_in;
        filter.id_not_in = self.id_not_in;
        filter.block_number = self.block_number;
        filter.block_number_not = self.block_number_not;
        filter.block_number_gt = self.block_number_gt;
        filter.block_number_lt = self.block_number_lt;
        filter.block_number_gte = self.block_number_gte;
        filter.block_number_lte = self.block_number_lte;
        filter.block_number_in = self.block_number_in;
        filter.block_number_not_in = self.block_number_not_in;
        filter.transaction_id = self.transaction_id;
        filter.transaction_id_not = self.transaction_id_not;
        filter.transaction_id_gt = self.transaction_id_gt;
        filter.transaction_id_lt = self.transaction_id_lt;
        filter.transaction_id_gte = self.transaction_id_gte;
        filter.transaction_id_lte = self.transaction_id_lte;
        filter.transaction_id_in = self.transaction_id_in;
        filter.transaction_id_not_in = self.transaction_id_not_in;
        filter.transaction_id_contains = self.transaction_id_contains;
        filter.transaction_id_not_contains = self.transaction_id_not_contains;
    }
}

pub(crate) trait ApplyEventFilter {
    fn apply(self, filter: &mut EventFilter);
}
