use storage::EventFilter as StorageEventFilter;

use super::EventFilter;

impl EventFilter {
    pub(crate) fn into_domain_filter(self) -> StorageEventFilter {
        let parent_id = self.parent_id.clone();
        self.into_storage_filter(parent_id)
    }

    pub(crate) fn into_registration_filter(self) -> StorageEventFilter {
        let parent_id = self.parent_id.clone();
        self.into_storage_filter(parent_id)
    }

    pub(crate) fn into_resolver_filter(self) -> StorageEventFilter {
        let parent_id = self.parent_id.clone();
        self.into_storage_filter(parent_id)
    }

    fn into_storage_filter(self, parent_id: Option<String>) -> StorageEventFilter {
        StorageEventFilter {
            id: self.id,
            id_not: self.id_not,
            id_gt: self.id_gt,
            id_lt: self.id_lt,
            id_gte: self.id_gte,
            id_lte: self.id_lte,
            id_in: self.id_in,
            id_not_in: self.id_not_in,
            parent_id,
            block_number: self.block_number,
            block_number_not: self.block_number_not,
            block_number_gt: self.block_number_gt,
            block_number_lt: self.block_number_lt,
            block_number_gte: self.block_number_gte,
            block_number_lte: self.block_number_lte,
            block_number_in: self.block_number_in,
            block_number_not_in: self.block_number_not_in,
            transaction_id: self.transaction_id,
            transaction_id_not: self.transaction_id_not,
            transaction_id_gt: self.transaction_id_gt,
            transaction_id_lt: self.transaction_id_lt,
            transaction_id_gte: self.transaction_id_gte,
            transaction_id_lte: self.transaction_id_lte,
            transaction_id_in: self.transaction_id_in,
            transaction_id_not_in: self.transaction_id_not_in,
            transaction_id_contains: self.transaction_id_contains,
            transaction_id_not_contains: self.transaction_id_not_contains,
            owner_id: self.owner_id,
            owner_id_not: self.owner_id_not,
            owner_id_gt: self.owner_id_gt,
            owner_id_lt: self.owner_id_lt,
            owner_id_gte: self.owner_id_gte,
            owner_id_lte: self.owner_id_lte,
            owner_id_in: self.owner_id_in,
            owner_id_not_in: self.owner_id_not_in,
            owner_id_contains: self.owner_id_contains,
            owner_id_not_contains: self.owner_id_not_contains,
            parent_domain_id: self.parent_domain_id,
            resolver_id: self.resolver_id,
            registrant_id: self.registrant_id,
            new_owner_id: self.new_owner_id,
            addr_id: self.addr_id,
            addr_id_not: self.addr_id_not,
            addr_id_gt: self.addr_id_gt,
            addr_id_lt: self.addr_id_lt,
            addr_id_gte: self.addr_id_gte,
            addr_id_lte: self.addr_id_lte,
            addr_id_in: self.addr_id_in,
            addr_id_not_in: self.addr_id_not_in,
            addr_id_contains: self.addr_id_contains,
            addr_id_not_contains: self.addr_id_not_contains,
            name: self.name,
            name_not: self.name_not,
            name_gt: self.name_gt,
            name_lt: self.name_lt,
            name_gte: self.name_gte,
            name_lte: self.name_lte,
            name_in: self.name_in,
            name_not_in: self.name_not_in,
            name_contains: self.name_contains,
            name_contains_nocase: self.name_contains_nocase,
            name_not_contains: self.name_not_contains,
            name_not_contains_nocase: self.name_not_contains_nocase,
            name_starts_with: self.name_starts_with,
            name_starts_with_nocase: self.name_starts_with_nocase,
            name_not_starts_with: self.name_not_starts_with,
            name_not_starts_with_nocase: self.name_not_starts_with_nocase,
            name_ends_with: self.name_ends_with,
            name_ends_with_nocase: self.name_ends_with_nocase,
            name_not_ends_with: self.name_not_ends_with,
            name_not_ends_with_nocase: self.name_not_ends_with_nocase,
            fuses: self.fuses,
            fuses_not: self.fuses_not,
            fuses_gt: self.fuses_gt,
            fuses_lt: self.fuses_lt,
            fuses_gte: self.fuses_gte,
            fuses_lte: self.fuses_lte,
            fuses_in: self.fuses_in,
            fuses_not_in: self.fuses_not_in,
            ttl: self.ttl,
            ttl_not: self.ttl_not,
            ttl_gt: self.ttl_gt,
            ttl_lt: self.ttl_lt,
            ttl_gte: self.ttl_gte,
            ttl_lte: self.ttl_lte,
            ttl_in: self.ttl_in,
            ttl_not_in: self.ttl_not_in,
            expiry_date: self.expiry_date,
            expiry_date_not: self.expiry_date_not,
            expiry_date_gt: self.expiry_date_gt,
            expiry_date_lt: self.expiry_date_lt,
            expiry_date_gte: self.expiry_date_gte,
            expiry_date_lte: self.expiry_date_lte,
            expiry_date_in: self.expiry_date_in,
            expiry_date_not_in: self.expiry_date_not_in,
            coin_type: self.coin_type,
            coin_type_not: self.coin_type_not,
            coin_type_gt: self.coin_type_gt,
            coin_type_lt: self.coin_type_lt,
            coin_type_gte: self.coin_type_gte,
            coin_type_lte: self.coin_type_lte,
            coin_type_in: self.coin_type_in,
            coin_type_not_in: self.coin_type_not_in,
            content_type: self.content_type,
            content_type_not: self.content_type_not,
            content_type_gt: self.content_type_gt,
            content_type_lt: self.content_type_lt,
            content_type_gte: self.content_type_gte,
            content_type_lte: self.content_type_lte,
            content_type_in: self.content_type_in,
            content_type_not_in: self.content_type_not_in,
            x: self.x,
            x_not: self.x_not,
            x_gt: self.x_gt,
            x_lt: self.x_lt,
            x_gte: self.x_gte,
            x_lte: self.x_lte,
            x_in: self.x_in,
            x_not_in: self.x_not_in,
            x_contains: self.x_contains,
            x_not_contains: self.x_not_contains,
            y: self.y,
            y_not: self.y_not,
            y_gt: self.y_gt,
            y_lt: self.y_lt,
            y_gte: self.y_gte,
            y_lte: self.y_lte,
            y_in: self.y_in,
            y_not_in: self.y_not_in,
            y_contains: self.y_contains,
            y_not_contains: self.y_not_contains,
            key: self.key,
            key_not: self.key_not,
            key_gt: self.key_gt,
            key_lt: self.key_lt,
            key_gte: self.key_gte,
            key_lte: self.key_lte,
            key_in: self.key_in,
            key_not_in: self.key_not_in,
            key_contains: self.key_contains,
            key_contains_nocase: self.key_contains_nocase,
            key_not_contains: self.key_not_contains,
            key_not_contains_nocase: self.key_not_contains_nocase,
            key_starts_with: self.key_starts_with,
            key_starts_with_nocase: self.key_starts_with_nocase,
            key_not_starts_with: self.key_not_starts_with,
            key_not_starts_with_nocase: self.key_not_starts_with_nocase,
            key_ends_with: self.key_ends_with,
            key_ends_with_nocase: self.key_ends_with_nocase,
            key_not_ends_with: self.key_not_ends_with,
            key_not_ends_with_nocase: self.key_not_ends_with_nocase,
            value: self.value,
            value_not: self.value_not,
            value_gt: self.value_gt,
            value_lt: self.value_lt,
            value_gte: self.value_gte,
            value_lte: self.value_lte,
            value_in: self.value_in,
            value_not_in: self.value_not_in,
            value_contains: self.value_contains,
            value_contains_nocase: self.value_contains_nocase,
            value_not_contains: self.value_not_contains,
            value_not_contains_nocase: self.value_not_contains_nocase,
            value_starts_with: self.value_starts_with,
            value_starts_with_nocase: self.value_starts_with_nocase,
            value_not_starts_with: self.value_not_starts_with,
            value_not_starts_with_nocase: self.value_not_starts_with_nocase,
            value_ends_with: self.value_ends_with,
            value_ends_with_nocase: self.value_ends_with_nocase,
            value_not_ends_with: self.value_not_ends_with,
            value_not_ends_with_nocase: self.value_not_ends_with_nocase,
            hash: self.hash,
            hash_not: self.hash_not,
            hash_gt: self.hash_gt,
            hash_lt: self.hash_lt,
            hash_gte: self.hash_gte,
            hash_lte: self.hash_lte,
            hash_in: self.hash_in,
            hash_not_in: self.hash_not_in,
            hash_contains: self.hash_contains,
            hash_not_contains: self.hash_not_contains,
            interface_id: self.interface_id,
            interface_id_not: self.interface_id_not,
            interface_id_gt: self.interface_id_gt,
            interface_id_lt: self.interface_id_lt,
            interface_id_gte: self.interface_id_gte,
            interface_id_lte: self.interface_id_lte,
            interface_id_in: self.interface_id_in,
            interface_id_not_in: self.interface_id_not_in,
            interface_id_contains: self.interface_id_contains,
            interface_id_not_contains: self.interface_id_not_contains,
            implementer: self.implementer,
            implementer_not: self.implementer_not,
            implementer_gt: self.implementer_gt,
            implementer_lt: self.implementer_lt,
            implementer_gte: self.implementer_gte,
            implementer_lte: self.implementer_lte,
            implementer_in: self.implementer_in,
            implementer_not_in: self.implementer_not_in,
            implementer_contains: self.implementer_contains,
            implementer_not_contains: self.implementer_not_contains,
            target: self.target,
            target_not: self.target_not,
            target_gt: self.target_gt,
            target_lt: self.target_lt,
            target_gte: self.target_gte,
            target_lte: self.target_lte,
            target_in: self.target_in,
            target_not_in: self.target_not_in,
            target_contains: self.target_contains,
            target_not_contains: self.target_not_contains,
            is_authorized: self.is_authorized,
            is_authorized_not: self.is_authorized_not,
            is_authorized_in: self.is_authorized_in,
            is_authorized_not_in: self.is_authorized_not_in,
            version: self.version,
            version_not: self.version_not,
            version_gt: self.version_gt,
            version_lt: self.version_lt,
            version_gte: self.version_gte,
            version_lte: self.version_lte,
            version_in: self.version_in,
            version_not_in: self.version_not_in,
        }
    }
}
