use crate::filters::BlockChangedFilter;
use crate::filters::DomainEventFilter;
use crate::filters::DomainFilter;
use crate::filters::RegistrationFilter;
use crate::filters::WrappedDomainFilter;
use async_graphql::InputObject;

#[derive(Debug, Clone, InputObject, Default)]
pub(crate) struct DomainFilterExtras {
    #[graphql(name = "id_gt")]
    pub id_gt: Option<String>,
    #[graphql(name = "id_lt")]
    pub id_lt: Option<String>,
    #[graphql(name = "id_gte")]
    pub id_gte: Option<String>,
    #[graphql(name = "id_lte")]
    pub id_lte: Option<String>,
    #[graphql(name = "name_not")]
    pub name_not: Option<String>,
    #[graphql(name = "name_gt")]
    pub name_gt: Option<String>,
    #[graphql(name = "name_lt")]
    pub name_lt: Option<String>,
    #[graphql(name = "name_gte")]
    pub name_gte: Option<String>,
    #[graphql(name = "name_lte")]
    pub name_lte: Option<String>,
    #[graphql(name = "name_in")]
    pub name_in: Option<Vec<String>>,
    #[graphql(name = "name_not_in")]
    pub name_not_in: Option<Vec<String>>,
    #[graphql(name = "name_not_contains")]
    pub name_not_contains: Option<String>,
    #[graphql(name = "name_not_contains_nocase")]
    pub name_not_contains_nocase: Option<String>,
    #[graphql(name = "name_starts_with_nocase")]
    pub name_starts_with_nocase: Option<String>,
    #[graphql(name = "name_not_starts_with")]
    pub name_not_starts_with: Option<String>,
    #[graphql(name = "name_not_starts_with_nocase")]
    pub name_not_starts_with_nocase: Option<String>,
    #[graphql(name = "name_ends_with_nocase")]
    pub name_ends_with_nocase: Option<String>,
    #[graphql(name = "name_not_ends_with")]
    pub name_not_ends_with: Option<String>,
    #[graphql(name = "name_not_ends_with_nocase")]
    pub name_not_ends_with_nocase: Option<String>,
    #[graphql(name = "labelName_not")]
    pub label_name_not: Option<String>,
    #[graphql(name = "labelName_gt")]
    pub label_name_gt: Option<String>,
    #[graphql(name = "labelName_lt")]
    pub label_name_lt: Option<String>,
    #[graphql(name = "labelName_gte")]
    pub label_name_gte: Option<String>,
    #[graphql(name = "labelName_lte")]
    pub label_name_lte: Option<String>,
    #[graphql(name = "labelName_in")]
    pub label_name_in: Option<Vec<String>>,
    #[graphql(name = "labelName_not_in")]
    pub label_name_not_in: Option<Vec<String>>,
    #[graphql(name = "labelName_not_contains")]
    pub label_name_not_contains: Option<String>,
    #[graphql(name = "labelName_not_contains_nocase")]
    pub label_name_not_contains_nocase: Option<String>,
    #[graphql(name = "labelName_starts_with_nocase")]
    pub label_name_starts_with_nocase: Option<String>,
    #[graphql(name = "labelName_not_starts_with")]
    pub label_name_not_starts_with: Option<String>,
    #[graphql(name = "labelName_not_starts_with_nocase")]
    pub label_name_not_starts_with_nocase: Option<String>,
    #[graphql(name = "labelName_ends_with_nocase")]
    pub label_name_ends_with_nocase: Option<String>,
    #[graphql(name = "labelName_not_ends_with")]
    pub label_name_not_ends_with: Option<String>,
    #[graphql(name = "labelName_not_ends_with_nocase")]
    pub label_name_not_ends_with_nocase: Option<String>,
    #[graphql(name = "labelhash_gt")]
    pub labelhash_gt: Option<String>,
    #[graphql(name = "labelhash_lt")]
    pub labelhash_lt: Option<String>,
    #[graphql(name = "labelhash_gte")]
    pub labelhash_gte: Option<String>,
    #[graphql(name = "labelhash_lte")]
    pub labelhash_lte: Option<String>,
    #[graphql(name = "labelhash_contains")]
    pub labelhash_contains: Option<String>,
    #[graphql(name = "labelhash_not_contains")]
    pub labelhash_not_contains: Option<String>,
    #[graphql(name = "parent_not")]
    pub parent_not: Option<String>,
    #[graphql(name = "parent_gt")]
    pub parent_gt: Option<String>,
    #[graphql(name = "parent_lt")]
    pub parent_lt: Option<String>,
    #[graphql(name = "parent_gte")]
    pub parent_gte: Option<String>,
    #[graphql(name = "parent_lte")]
    pub parent_lte: Option<String>,
    #[graphql(name = "parent_in")]
    pub parent_in: Option<Vec<String>>,
    #[graphql(name = "parent_not_in")]
    pub parent_not_in: Option<Vec<String>>,
    #[graphql(name = "parent_contains")]
    pub parent_contains: Option<String>,
    #[graphql(name = "parent_contains_nocase")]
    pub parent_contains_nocase: Option<String>,
    #[graphql(name = "parent_not_contains")]
    pub parent_not_contains: Option<String>,
    #[graphql(name = "parent_not_contains_nocase")]
    pub parent_not_contains_nocase: Option<String>,
    #[graphql(name = "parent_starts_with")]
    pub parent_starts_with: Option<String>,
    #[graphql(name = "parent_starts_with_nocase")]
    pub parent_starts_with_nocase: Option<String>,
    #[graphql(name = "parent_not_starts_with")]
    pub parent_not_starts_with: Option<String>,
    #[graphql(name = "parent_not_starts_with_nocase")]
    pub parent_not_starts_with_nocase: Option<String>,
    #[graphql(name = "parent_ends_with")]
    pub parent_ends_with: Option<String>,
    #[graphql(name = "parent_ends_with_nocase")]
    pub parent_ends_with_nocase: Option<String>,
    #[graphql(name = "parent_not_ends_with")]
    pub parent_not_ends_with: Option<String>,
    #[graphql(name = "parent_not_ends_with_nocase")]
    pub parent_not_ends_with_nocase: Option<String>,
    #[graphql(name = "subdomains_")]
    pub subdomains_: Option<Box<DomainFilter>>,
    #[graphql(name = "subdomainCount_not")]
    pub subdomain_count_not: Option<String>,
    #[graphql(name = "subdomainCount_in")]
    pub subdomain_count_in: Option<Vec<i32>>,
    #[graphql(name = "subdomainCount_not_in")]
    pub subdomain_count_not_in: Option<Vec<i32>>,
    #[graphql(name = "resolvedAddress_not")]
    pub resolved_address_not: Option<String>,
    #[graphql(name = "resolvedAddress_gt")]
    pub resolved_address_gt: Option<String>,
    #[graphql(name = "resolvedAddress_lt")]
    pub resolved_address_lt: Option<String>,
    #[graphql(name = "resolvedAddress_gte")]
    pub resolved_address_gte: Option<String>,
    #[graphql(name = "resolvedAddress_lte")]
    pub resolved_address_lte: Option<String>,
    #[graphql(name = "resolvedAddress_in")]
    pub resolved_address_in: Option<Vec<String>>,
    #[graphql(name = "resolvedAddress_not_in")]
    pub resolved_address_not_in: Option<Vec<String>>,
    #[graphql(name = "resolvedAddress_contains")]
    pub resolved_address_contains: Option<String>,
    #[graphql(name = "resolvedAddress_contains_nocase")]
    pub resolved_address_contains_nocase: Option<String>,
    #[graphql(name = "resolvedAddress_not_contains")]
    pub resolved_address_not_contains: Option<String>,
    #[graphql(name = "resolvedAddress_not_contains_nocase")]
    pub resolved_address_not_contains_nocase: Option<String>,
    #[graphql(name = "resolvedAddress_starts_with")]
    pub resolved_address_starts_with: Option<String>,
    #[graphql(name = "resolvedAddress_starts_with_nocase")]
    pub resolved_address_starts_with_nocase: Option<String>,
    #[graphql(name = "resolvedAddress_not_starts_with")]
    pub resolved_address_not_starts_with: Option<String>,
    #[graphql(name = "resolvedAddress_not_starts_with_nocase")]
    pub resolved_address_not_starts_with_nocase: Option<String>,
    #[graphql(name = "resolvedAddress_ends_with")]
    pub resolved_address_ends_with: Option<String>,
    #[graphql(name = "resolvedAddress_ends_with_nocase")]
    pub resolved_address_ends_with_nocase: Option<String>,
    #[graphql(name = "resolvedAddress_not_ends_with")]
    pub resolved_address_not_ends_with: Option<String>,
    #[graphql(name = "resolvedAddress_not_ends_with_nocase")]
    pub resolved_address_not_ends_with_nocase: Option<String>,
    #[graphql(name = "resolver_not")]
    pub resolver_not: Option<String>,
    #[graphql(name = "resolver_gt")]
    pub resolver_gt: Option<String>,
    #[graphql(name = "resolver_lt")]
    pub resolver_lt: Option<String>,
    #[graphql(name = "resolver_gte")]
    pub resolver_gte: Option<String>,
    #[graphql(name = "resolver_lte")]
    pub resolver_lte: Option<String>,
    #[graphql(name = "resolver_in")]
    pub resolver_in: Option<Vec<String>>,
    #[graphql(name = "resolver_not_in")]
    pub resolver_not_in: Option<Vec<String>>,
    #[graphql(name = "resolver_contains")]
    pub resolver_contains: Option<String>,
    #[graphql(name = "resolver_contains_nocase")]
    pub resolver_contains_nocase: Option<String>,
    #[graphql(name = "resolver_not_contains")]
    pub resolver_not_contains: Option<String>,
    #[graphql(name = "resolver_not_contains_nocase")]
    pub resolver_not_contains_nocase: Option<String>,
    #[graphql(name = "resolver_starts_with")]
    pub resolver_starts_with: Option<String>,
    #[graphql(name = "resolver_starts_with_nocase")]
    pub resolver_starts_with_nocase: Option<String>,
    #[graphql(name = "resolver_not_starts_with")]
    pub resolver_not_starts_with: Option<String>,
    #[graphql(name = "resolver_not_starts_with_nocase")]
    pub resolver_not_starts_with_nocase: Option<String>,
    #[graphql(name = "resolver_ends_with")]
    pub resolver_ends_with: Option<String>,
    #[graphql(name = "resolver_ends_with_nocase")]
    pub resolver_ends_with_nocase: Option<String>,
    #[graphql(name = "resolver_not_ends_with")]
    pub resolver_not_ends_with: Option<String>,
    #[graphql(name = "resolver_not_ends_with_nocase")]
    pub resolver_not_ends_with_nocase: Option<String>,
    #[graphql(name = "ttl_not")]
    pub ttl_not: Option<String>,
    #[graphql(name = "ttl_in")]
    pub ttl_in: Option<Vec<String>>,
    #[graphql(name = "ttl_not_in")]
    pub ttl_not_in: Option<Vec<String>>,
    #[graphql(name = "isMigrated_in")]
    pub is_migrated_in: Option<Vec<bool>>,
    #[graphql(name = "isMigrated_not_in")]
    pub is_migrated_not_in: Option<Vec<bool>>,
    #[graphql(name = "createdAt_not")]
    pub created_at_not: Option<String>,
    #[graphql(name = "createdAt_in")]
    pub created_at_in: Option<Vec<String>>,
    #[graphql(name = "createdAt_not_in")]
    pub created_at_not_in: Option<Vec<String>>,
    #[graphql(name = "owner_not")]
    pub owner_not: Option<String>,
    #[graphql(name = "owner_gt")]
    pub owner_gt: Option<String>,
    #[graphql(name = "owner_lt")]
    pub owner_lt: Option<String>,
    #[graphql(name = "owner_gte")]
    pub owner_gte: Option<String>,
    #[graphql(name = "owner_lte")]
    pub owner_lte: Option<String>,
    #[graphql(name = "owner_in")]
    pub owner_in: Option<Vec<String>>,
    #[graphql(name = "owner_not_in")]
    pub owner_not_in: Option<Vec<String>>,
    #[graphql(name = "owner_contains")]
    pub owner_contains: Option<String>,
    #[graphql(name = "owner_contains_nocase")]
    pub owner_contains_nocase: Option<String>,
    #[graphql(name = "owner_not_contains")]
    pub owner_not_contains: Option<String>,
    #[graphql(name = "owner_not_contains_nocase")]
    pub owner_not_contains_nocase: Option<String>,
    #[graphql(name = "owner_starts_with")]
    pub owner_starts_with: Option<String>,
    #[graphql(name = "owner_starts_with_nocase")]
    pub owner_starts_with_nocase: Option<String>,
    #[graphql(name = "owner_not_starts_with")]
    pub owner_not_starts_with: Option<String>,
    #[graphql(name = "owner_not_starts_with_nocase")]
    pub owner_not_starts_with_nocase: Option<String>,
    #[graphql(name = "owner_ends_with")]
    pub owner_ends_with: Option<String>,
    #[graphql(name = "owner_ends_with_nocase")]
    pub owner_ends_with_nocase: Option<String>,
    #[graphql(name = "owner_not_ends_with")]
    pub owner_not_ends_with: Option<String>,
    #[graphql(name = "owner_not_ends_with_nocase")]
    pub owner_not_ends_with_nocase: Option<String>,
    #[graphql(name = "registrant_not")]
    pub registrant_not: Option<String>,
    #[graphql(name = "registrant_gt")]
    pub registrant_gt: Option<String>,
    #[graphql(name = "registrant_lt")]
    pub registrant_lt: Option<String>,
    #[graphql(name = "registrant_gte")]
    pub registrant_gte: Option<String>,
    #[graphql(name = "registrant_lte")]
    pub registrant_lte: Option<String>,
    #[graphql(name = "registrant_in")]
    pub registrant_in: Option<Vec<String>>,
    #[graphql(name = "registrant_not_in")]
    pub registrant_not_in: Option<Vec<String>>,
    #[graphql(name = "registrant_contains")]
    pub registrant_contains: Option<String>,
    #[graphql(name = "registrant_contains_nocase")]
    pub registrant_contains_nocase: Option<String>,
    #[graphql(name = "registrant_not_contains")]
    pub registrant_not_contains: Option<String>,
    #[graphql(name = "registrant_not_contains_nocase")]
    pub registrant_not_contains_nocase: Option<String>,
    #[graphql(name = "registrant_starts_with")]
    pub registrant_starts_with: Option<String>,
    #[graphql(name = "registrant_starts_with_nocase")]
    pub registrant_starts_with_nocase: Option<String>,
    #[graphql(name = "registrant_not_starts_with")]
    pub registrant_not_starts_with: Option<String>,
    #[graphql(name = "registrant_not_starts_with_nocase")]
    pub registrant_not_starts_with_nocase: Option<String>,
    #[graphql(name = "registrant_ends_with")]
    pub registrant_ends_with: Option<String>,
    #[graphql(name = "registrant_ends_with_nocase")]
    pub registrant_ends_with_nocase: Option<String>,
    #[graphql(name = "registrant_not_ends_with")]
    pub registrant_not_ends_with: Option<String>,
    #[graphql(name = "registrant_not_ends_with_nocase")]
    pub registrant_not_ends_with_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_not")]
    pub wrapped_owner_not: Option<String>,
    #[graphql(name = "wrappedOwner_gt")]
    pub wrapped_owner_gt: Option<String>,
    #[graphql(name = "wrappedOwner_lt")]
    pub wrapped_owner_lt: Option<String>,
    #[graphql(name = "wrappedOwner_gte")]
    pub wrapped_owner_gte: Option<String>,
    #[graphql(name = "wrappedOwner_lte")]
    pub wrapped_owner_lte: Option<String>,
    #[graphql(name = "wrappedOwner_in")]
    pub wrapped_owner_in: Option<Vec<String>>,
    #[graphql(name = "wrappedOwner_not_in")]
    pub wrapped_owner_not_in: Option<Vec<String>>,
    #[graphql(name = "wrappedOwner_contains")]
    pub wrapped_owner_contains: Option<String>,
    #[graphql(name = "wrappedOwner_contains_nocase")]
    pub wrapped_owner_contains_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_not_contains")]
    pub wrapped_owner_not_contains: Option<String>,
    #[graphql(name = "wrappedOwner_not_contains_nocase")]
    pub wrapped_owner_not_contains_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_starts_with")]
    pub wrapped_owner_starts_with: Option<String>,
    #[graphql(name = "wrappedOwner_starts_with_nocase")]
    pub wrapped_owner_starts_with_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_not_starts_with")]
    pub wrapped_owner_not_starts_with: Option<String>,
    #[graphql(name = "wrappedOwner_not_starts_with_nocase")]
    pub wrapped_owner_not_starts_with_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_ends_with")]
    pub wrapped_owner_ends_with: Option<String>,
    #[graphql(name = "wrappedOwner_ends_with_nocase")]
    pub wrapped_owner_ends_with_nocase: Option<String>,
    #[graphql(name = "wrappedOwner_not_ends_with")]
    pub wrapped_owner_not_ends_with: Option<String>,
    #[graphql(name = "wrappedOwner_not_ends_with_nocase")]
    pub wrapped_owner_not_ends_with_nocase: Option<String>,
    #[graphql(name = "expiryDate_not")]
    pub expiry_date_not: Option<String>,
    #[graphql(name = "expiryDate_in")]
    pub expiry_date_in: Option<Vec<String>>,
    #[graphql(name = "expiryDate_not_in")]
    pub expiry_date_not_in: Option<Vec<String>>,
    #[graphql(name = "registration_")]
    pub registration_: Option<Box<RegistrationFilter>>,
    #[graphql(name = "wrappedDomain_")]
    pub wrapped_domain_: Option<Box<WrappedDomainFilter>>,
    #[graphql(name = "events_")]
    pub events_: Option<Box<DomainEventFilter>>,
    #[graphql(name = "_change_block")]
    pub change_block: Option<BlockChangedFilter>,
    #[graphql(name = "and")]
    pub and: Option<Vec<DomainFilter>>,
    #[graphql(name = "or")]
    pub or: Option<Vec<DomainFilter>>,
}
