use crate::filters::BlockChangedFilter;
use crate::filters::RegistrationEventFilter;
use crate::filters::RegistrationFilter;
use async_graphql::InputObject;

#[derive(Debug, Clone, InputObject, Default)]
pub(crate) struct RegistrationFilterExtras {
    #[graphql(name = "id_gt")]
    pub id_gt: Option<String>,
    #[graphql(name = "id_lt")]
    pub id_lt: Option<String>,
    #[graphql(name = "id_gte")]
    pub id_gte: Option<String>,
    #[graphql(name = "id_lte")]
    pub id_lte: Option<String>,
    #[graphql(name = "domain_not")]
    pub domain_not: Option<String>,
    #[graphql(name = "domain_gt")]
    pub domain_gt: Option<String>,
    #[graphql(name = "domain_lt")]
    pub domain_lt: Option<String>,
    #[graphql(name = "domain_gte")]
    pub domain_gte: Option<String>,
    #[graphql(name = "domain_lte")]
    pub domain_lte: Option<String>,
    #[graphql(name = "domain_in")]
    pub domain_in: Option<Vec<String>>,
    #[graphql(name = "domain_not_in")]
    pub domain_not_in: Option<Vec<String>>,
    #[graphql(name = "domain_contains")]
    pub domain_contains: Option<String>,
    #[graphql(name = "domain_contains_nocase")]
    pub domain_contains_nocase: Option<String>,
    #[graphql(name = "domain_not_contains")]
    pub domain_not_contains: Option<String>,
    #[graphql(name = "domain_not_contains_nocase")]
    pub domain_not_contains_nocase: Option<String>,
    #[graphql(name = "domain_starts_with")]
    pub domain_starts_with: Option<String>,
    #[graphql(name = "domain_starts_with_nocase")]
    pub domain_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_not_starts_with")]
    pub domain_not_starts_with: Option<String>,
    #[graphql(name = "domain_not_starts_with_nocase")]
    pub domain_not_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_ends_with")]
    pub domain_ends_with: Option<String>,
    #[graphql(name = "domain_ends_with_nocase")]
    pub domain_ends_with_nocase: Option<String>,
    #[graphql(name = "domain_not_ends_with")]
    pub domain_not_ends_with: Option<String>,
    #[graphql(name = "domain_not_ends_with_nocase")]
    pub domain_not_ends_with_nocase: Option<String>,
    #[graphql(name = "registrationDate_not")]
    pub registration_date_not: Option<String>,
    #[graphql(name = "registrationDate_in")]
    pub registration_date_in: Option<Vec<String>>,
    #[graphql(name = "registrationDate_not_in")]
    pub registration_date_not_in: Option<Vec<String>>,
    #[graphql(name = "expiryDate_not")]
    pub expiry_date_not: Option<String>,
    #[graphql(name = "expiryDate_in")]
    pub expiry_date_in: Option<Vec<String>>,
    #[graphql(name = "expiryDate_not_in")]
    pub expiry_date_not_in: Option<Vec<String>>,
    #[graphql(name = "cost_not")]
    pub cost_not: Option<String>,
    #[graphql(name = "cost_in")]
    pub cost_in: Option<Vec<String>>,
    #[graphql(name = "cost_not_in")]
    pub cost_not_in: Option<Vec<String>>,
    #[graphql(name = "registrant_not")]
    pub registrant_not: Option<String>,
    #[graphql(name = "registrant_gt")]
    pub registrant_gt: Option<String>,
    #[graphql(name = "registrant_lt")]
    pub registrant_lt: Option<String>,
    #[graphql(name = "registrant_gte")]
    pub registrant_gte: Option<String>,
    #[graphql(name = "registrant_lte")]
    pub registrant_lte: Option<String>,
    #[graphql(name = "registrant_in")]
    pub registrant_in: Option<Vec<String>>,
    #[graphql(name = "registrant_not_in")]
    pub registrant_not_in: Option<Vec<String>>,
    #[graphql(name = "registrant_contains")]
    pub registrant_contains: Option<String>,
    #[graphql(name = "registrant_contains_nocase")]
    pub registrant_contains_nocase: Option<String>,
    #[graphql(name = "registrant_not_contains")]
    pub registrant_not_contains: Option<String>,
    #[graphql(name = "registrant_not_contains_nocase")]
    pub registrant_not_contains_nocase: Option<String>,
    #[graphql(name = "registrant_starts_with")]
    pub registrant_starts_with: Option<String>,
    #[graphql(name = "registrant_starts_with_nocase")]
    pub registrant_starts_with_nocase: Option<String>,
    #[graphql(name = "registrant_not_starts_with")]
    pub registrant_not_starts_with: Option<String>,
    #[graphql(name = "registrant_not_starts_with_nocase")]
    pub registrant_not_starts_with_nocase: Option<String>,
    #[graphql(name = "registrant_ends_with")]
    pub registrant_ends_with: Option<String>,
    #[graphql(name = "registrant_ends_with_nocase")]
    pub registrant_ends_with_nocase: Option<String>,
    #[graphql(name = "registrant_not_ends_with")]
    pub registrant_not_ends_with: Option<String>,
    #[graphql(name = "registrant_not_ends_with_nocase")]
    pub registrant_not_ends_with_nocase: Option<String>,
    #[graphql(name = "labelName_not")]
    pub label_name_not: Option<String>,
    #[graphql(name = "labelName_gt")]
    pub label_name_gt: Option<String>,
    #[graphql(name = "labelName_lt")]
    pub label_name_lt: Option<String>,
    #[graphql(name = "labelName_gte")]
    pub label_name_gte: Option<String>,
    #[graphql(name = "labelName_lte")]
    pub label_name_lte: Option<String>,
    #[graphql(name = "labelName_in")]
    pub label_name_in: Option<Vec<String>>,
    #[graphql(name = "labelName_not_in")]
    pub label_name_not_in: Option<Vec<String>>,
    #[graphql(name = "labelName_not_contains")]
    pub label_name_not_contains: Option<String>,
    #[graphql(name = "labelName_not_contains_nocase")]
    pub label_name_not_contains_nocase: Option<String>,
    #[graphql(name = "labelName_starts_with_nocase")]
    pub label_name_starts_with_nocase: Option<String>,
    #[graphql(name = "labelName_not_starts_with")]
    pub label_name_not_starts_with: Option<String>,
    #[graphql(name = "labelName_not_starts_with_nocase")]
    pub label_name_not_starts_with_nocase: Option<String>,
    #[graphql(name = "labelName_ends_with_nocase")]
    pub label_name_ends_with_nocase: Option<String>,
    #[graphql(name = "labelName_not_ends_with")]
    pub label_name_not_ends_with: Option<String>,
    #[graphql(name = "labelName_not_ends_with_nocase")]
    pub label_name_not_ends_with_nocase: Option<String>,
    #[graphql(name = "events_")]
    pub events_: Option<Box<RegistrationEventFilter>>,
    #[graphql(name = "_change_block")]
    pub change_block: Option<BlockChangedFilter>,
    #[graphql(name = "and")]
    pub and: Option<Vec<RegistrationFilter>>,
    #[graphql(name = "or")]
    pub or: Option<Vec<RegistrationFilter>>,
}
