use crate::filters::BlockChangedFilter;
use crate::filters::ResolverEventFilter;
use crate::filters::ResolverFilter;
use async_graphql::InputObject;

#[derive(Debug, Clone, InputObject, Default)]
pub(crate) struct ResolverFilterExtras {
    #[graphql(name = "id_gt")]
    pub id_gt: Option<String>,
    #[graphql(name = "id_lt")]
    pub id_lt: Option<String>,
    #[graphql(name = "id_gte")]
    pub id_gte: Option<String>,
    #[graphql(name = "id_lte")]
    pub id_lte: Option<String>,
    #[graphql(name = "domain_not")]
    pub domain_not: Option<String>,
    #[graphql(name = "domain_gt")]
    pub domain_gt: Option<String>,
    #[graphql(name = "domain_lt")]
    pub domain_lt: Option<String>,
    #[graphql(name = "domain_gte")]
    pub domain_gte: Option<String>,
    #[graphql(name = "domain_lte")]
    pub domain_lte: Option<String>,
    #[graphql(name = "domain_in")]
    pub domain_in: Option<Vec<String>>,
    #[graphql(name = "domain_not_in")]
    pub domain_not_in: Option<Vec<String>>,
    #[graphql(name = "domain_contains")]
    pub domain_contains: Option<String>,
    #[graphql(name = "domain_contains_nocase")]
    pub domain_contains_nocase: Option<String>,
    #[graphql(name = "domain_not_contains")]
    pub domain_not_contains: Option<String>,
    #[graphql(name = "domain_not_contains_nocase")]
    pub domain_not_contains_nocase: Option<String>,
    #[graphql(name = "domain_starts_with")]
    pub domain_starts_with: Option<String>,
    #[graphql(name = "domain_starts_with_nocase")]
    pub domain_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_not_starts_with")]
    pub domain_not_starts_with: Option<String>,
    #[graphql(name = "domain_not_starts_with_nocase")]
    pub domain_not_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_ends_with")]
    pub domain_ends_with: Option<String>,
    #[graphql(name = "domain_ends_with_nocase")]
    pub domain_ends_with_nocase: Option<String>,
    #[graphql(name = "domain_not_ends_with")]
    pub domain_not_ends_with: Option<String>,
    #[graphql(name = "domain_not_ends_with_nocase")]
    pub domain_not_ends_with_nocase: Option<String>,
    #[graphql(name = "address_not")]
    pub address_not: Option<String>,
    #[graphql(name = "address_gt")]
    pub address_gt: Option<String>,
    #[graphql(name = "address_lt")]
    pub address_lt: Option<String>,
    #[graphql(name = "address_gte")]
    pub address_gte: Option<String>,
    #[graphql(name = "address_lte")]
    pub address_lte: Option<String>,
    #[graphql(name = "address_not_in")]
    pub address_not_in: Option<Vec<String>>,
    #[graphql(name = "address_contains")]
    pub address_contains: Option<String>,
    #[graphql(name = "address_not_contains")]
    pub address_not_contains: Option<String>,
    #[graphql(name = "addr_not")]
    pub addr_not: Option<String>,
    #[graphql(name = "addr_gt")]
    pub addr_gt: Option<String>,
    #[graphql(name = "addr_lt")]
    pub addr_lt: Option<String>,
    #[graphql(name = "addr_gte")]
    pub addr_gte: Option<String>,
    #[graphql(name = "addr_lte")]
    pub addr_lte: Option<String>,
    #[graphql(name = "addr_in")]
    pub addr_in: Option<Vec<String>>,
    #[graphql(name = "addr_not_in")]
    pub addr_not_in: Option<Vec<String>>,
    #[graphql(name = "addr_contains")]
    pub addr_contains: Option<String>,
    #[graphql(name = "addr_contains_nocase")]
    pub addr_contains_nocase: Option<String>,
    #[graphql(name = "addr_not_contains")]
    pub addr_not_contains: Option<String>,
    #[graphql(name = "addr_not_contains_nocase")]
    pub addr_not_contains_nocase: Option<String>,
    #[graphql(name = "addr_starts_with")]
    pub addr_starts_with: Option<String>,
    #[graphql(name = "addr_starts_with_nocase")]
    pub addr_starts_with_nocase: Option<String>,
    #[graphql(name = "addr_not_starts_with")]
    pub addr_not_starts_with: Option<String>,
    #[graphql(name = "addr_not_starts_with_nocase")]
    pub addr_not_starts_with_nocase: Option<String>,
    #[graphql(name = "addr_ends_with")]
    pub addr_ends_with: Option<String>,
    #[graphql(name = "addr_ends_with_nocase")]
    pub addr_ends_with_nocase: Option<String>,
    #[graphql(name = "addr_not_ends_with")]
    pub addr_not_ends_with: Option<String>,
    #[graphql(name = "addr_not_ends_with_nocase")]
    pub addr_not_ends_with_nocase: Option<String>,
    #[graphql(name = "contentHash_gt")]
    pub content_hash_gt: Option<String>,
    #[graphql(name = "contentHash_lt")]
    pub content_hash_lt: Option<String>,
    #[graphql(name = "contentHash_gte")]
    pub content_hash_gte: Option<String>,
    #[graphql(name = "contentHash_lte")]
    pub content_hash_lte: Option<String>,
    #[graphql(name = "contentHash_not_contains")]
    pub content_hash_not_contains: Option<String>,
    #[graphql(name = "texts")]
    pub texts: Option<String>,
    #[graphql(name = "texts_not")]
    pub texts_not: Option<String>,
    #[graphql(name = "texts_contains_nocase")]
    pub texts_contains_nocase: Option<String>,
    #[graphql(name = "texts_not_contains")]
    pub texts_not_contains: Option<String>,
    #[graphql(name = "texts_not_contains_nocase")]
    pub texts_not_contains_nocase: Option<String>,
    #[graphql(name = "coinTypes")]
    pub coin_types: Option<String>,
    #[graphql(name = "coinTypes_not")]
    pub coin_types_not: Option<String>,
    #[graphql(name = "coinTypes_contains_nocase")]
    pub coin_types_contains_nocase: Option<String>,
    #[graphql(name = "coinTypes_not_contains")]
    pub coin_types_not_contains: Option<String>,
    #[graphql(name = "coinTypes_not_contains_nocase")]
    pub coin_types_not_contains_nocase: Option<String>,
    #[graphql(name = "events_")]
    pub events_: Option<Box<ResolverEventFilter>>,
    #[graphql(name = "_change_block")]
    pub change_block: Option<BlockChangedFilter>,
    #[graphql(name = "and")]
    pub and: Option<Vec<ResolverFilter>>,
    #[graphql(name = "or")]
    pub or: Option<Vec<ResolverFilter>>,
}
