use crate::filters::BlockChangedFilter;
use crate::filters::WrappedDomainFilter;
use async_graphql::InputObject;

#[derive(Debug, Clone, InputObject, Default)]
pub(crate) struct WrappedDomainFilterExtras {
    #[graphql(name = "id_gt")]
    pub id_gt: Option<String>,
    #[graphql(name = "id_lt")]
    pub id_lt: Option<String>,
    #[graphql(name = "id_gte")]
    pub id_gte: Option<String>,
    #[graphql(name = "id_lte")]
    pub id_lte: Option<String>,
    #[graphql(name = "domain_not")]
    pub domain_not: Option<String>,
    #[graphql(name = "domain_gt")]
    pub domain_gt: Option<String>,
    #[graphql(name = "domain_lt")]
    pub domain_lt: Option<String>,
    #[graphql(name = "domain_gte")]
    pub domain_gte: Option<String>,
    #[graphql(name = "domain_lte")]
    pub domain_lte: Option<String>,
    #[graphql(name = "domain_in")]
    pub domain_in: Option<Vec<String>>,
    #[graphql(name = "domain_not_in")]
    pub domain_not_in: Option<Vec<String>>,
    #[graphql(name = "domain_contains")]
    pub domain_contains: Option<String>,
    #[graphql(name = "domain_contains_nocase")]
    pub domain_contains_nocase: Option<String>,
    #[graphql(name = "domain_not_contains")]
    pub domain_not_contains: Option<String>,
    #[graphql(name = "domain_not_contains_nocase")]
    pub domain_not_contains_nocase: Option<String>,
    #[graphql(name = "domain_starts_with")]
    pub domain_starts_with: Option<String>,
    #[graphql(name = "domain_starts_with_nocase")]
    pub domain_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_not_starts_with")]
    pub domain_not_starts_with: Option<String>,
    #[graphql(name = "domain_not_starts_with_nocase")]
    pub domain_not_starts_with_nocase: Option<String>,
    #[graphql(name = "domain_ends_with")]
    pub domain_ends_with: Option<String>,
    #[graphql(name = "domain_ends_with_nocase")]
    pub domain_ends_with_nocase: Option<String>,
    #[graphql(name = "domain_not_ends_with")]
    pub domain_not_ends_with: Option<String>,
    #[graphql(name = "domain_not_ends_with_nocase")]
    pub domain_not_ends_with_nocase: Option<String>,
    #[graphql(name = "expiryDate_not")]
    pub expiry_date_not: Option<String>,
    #[graphql(name = "expiryDate_in")]
    pub expiry_date_in: Option<Vec<String>>,
    #[graphql(name = "expiryDate_not_in")]
    pub expiry_date_not_in: Option<Vec<String>>,
    #[graphql(name = "fuses_not")]
    pub fuses_not: Option<String>,
    #[graphql(name = "fuses_in")]
    pub fuses_in: Option<Vec<i32>>,
    #[graphql(name = "fuses_not_in")]
    pub fuses_not_in: Option<Vec<i32>>,
    #[graphql(name = "owner_not")]
    pub owner_not: Option<String>,
    #[graphql(name = "owner_gt")]
    pub owner_gt: Option<String>,
    #[graphql(name = "owner_lt")]
    pub owner_lt: Option<String>,
    #[graphql(name = "owner_gte")]
    pub owner_gte: Option<String>,
    #[graphql(name = "owner_lte")]
    pub owner_lte: Option<String>,
    #[graphql(name = "owner_in")]
    pub owner_in: Option<Vec<String>>,
    #[graphql(name = "owner_not_in")]
    pub owner_not_in: Option<Vec<String>>,
    #[graphql(name = "owner_contains")]
    pub owner_contains: Option<String>,
    #[graphql(name = "owner_contains_nocase")]
    pub owner_contains_nocase: Option<String>,
    #[graphql(name = "owner_not_contains")]
    pub owner_not_contains: Option<String>,
    #[graphql(name = "owner_not_contains_nocase")]
    pub owner_not_contains_nocase: Option<String>,
    #[graphql(name = "owner_starts_with")]
    pub owner_starts_with: Option<String>,
    #[graphql(name = "owner_starts_with_nocase")]
    pub owner_starts_with_nocase: Option<String>,
    #[graphql(name = "owner_not_starts_with")]
    pub owner_not_starts_with: Option<String>,
    #[graphql(name = "owner_not_starts_with_nocase")]
    pub owner_not_starts_with_nocase: Option<String>,
    #[graphql(name = "owner_ends_with")]
    pub owner_ends_with: Option<String>,
    #[graphql(name = "owner_ends_with_nocase")]
    pub owner_ends_with_nocase: Option<String>,
    #[graphql(name = "owner_not_ends_with")]
    pub owner_not_ends_with: Option<String>,
    #[graphql(name = "owner_not_ends_with_nocase")]
    pub owner_not_ends_with_nocase: Option<String>,
    #[graphql(name = "name_not")]
    pub name_not: Option<String>,
    #[graphql(name = "name_gt")]
    pub name_gt: Option<String>,
    #[graphql(name = "name_lt")]
    pub name_lt: Option<String>,
    #[graphql(name = "name_gte")]
    pub name_gte: Option<String>,
    #[graphql(name = "name_lte")]
    pub name_lte: Option<String>,
    #[graphql(name = "name_in")]
    pub name_in: Option<Vec<String>>,
    #[graphql(name = "name_not_in")]
    pub name_not_in: Option<Vec<String>>,
    #[graphql(name = "name_not_contains")]
    pub name_not_contains: Option<String>,
    #[graphql(name = "name_not_contains_nocase")]
    pub name_not_contains_nocase: Option<String>,
    #[graphql(name = "name_starts_with_nocase")]
    pub name_starts_with_nocase: Option<String>,
    #[graphql(name = "name_not_starts_with")]
    pub name_not_starts_with: Option<String>,
    #[graphql(name = "name_not_starts_with_nocase")]
    pub name_not_starts_with_nocase: Option<String>,
    #[graphql(name = "name_ends_with_nocase")]
    pub name_ends_with_nocase: Option<String>,
    #[graphql(name = "name_not_ends_with")]
    pub name_not_ends_with: Option<String>,
    #[graphql(name = "name_not_ends_with_nocase")]
    pub name_not_ends_with_nocase: Option<String>,
    #[graphql(name = "_change_block")]
    pub change_block: Option<BlockChangedFilter>,
    #[graphql(name = "and")]
    pub and: Option<Vec<WrappedDomainFilter>>,
    #[graphql(name = "or")]
    pub or: Option<Vec<WrappedDomainFilter>>,
}
